### ISSUE TITLE
FirebaseCrashlytics symbol is bundled with Binary

### ISSUE THREAD

**Issue by bdfox325** [EmergeTools/ETTrace#26]
When compiling application, getting issue:

```
objc[3368]: Class PodsDummy_FirebaseCrashlytics is implemented in both 
/private/var/containers/Bundle/Application/8700DB0D-AE97-4424-803C-98DA8B67E3B0/Robinhood.app/Frameworks/ETTrace.framework/ETTrace (0x11f526490) and 
/private/var/containers/Bundle/Application/8700DB0D-AE97-4424-803C-98DA8B67E3B0/Robinhood.app/Robinhood 
(0x10a88db68). One of the two will be used. Which one is undefined.
```

Is it necessary to compile FirebaseCrashlytics in the binary?

**Comment by bdfox325** [comment]
Hey. Yes, this is happening at runtime. We only package the app in our DEBUG builds so its not an issue for the end user.

**Comment by noahsmartin** [comment]
Thanks for explaining! We do plan to rename it. We are also evaluating switching to SwiftPM so will probably wait for that to complete, which can make renaming unnecessary. The only duplicated symbol appears to be the `PodsDummy_FirebaseCrashlytics` class which is just an empty class added by cocoapods, more details here: https://github.com/CocoaPods/CocoaPods/issues/1767. So I don't think there's anything to worry about in terms of wrong methods being called.

Since we use a local copy of the pod already (in the Unwinding folder) I suspect just renaming the pod in our Podfile would prevent the warning. So if you're interested you could try that out as a solution until we try switching to SwiftPM

**Comment by noahsmartin** [comment]
Hi @bdfox325 @KhaosT We have just released an update that switches to using Swift Package Manager for building the xcframework, you can now link to the new framework, or install it directly as a SPM dependency. There won't be this Firebase class included either way. Let us know if this works for you!
